import { Geist, Geist_Mono } from "next/font/google";
import "./assets/css/style.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">


      <body className="min-h-full flex flex-col" suppressHydrationWarning>

        <Header/>

        {children}


        <Footer/>
      </body>

    </html>
  );
}
